// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcymwqhvkbgttmhvdkfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjeW13cWh2a2JndHRtaHZka2ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjI4MjIsImV4cCI6MjA1NTc5ODgyMn0.w0Hhny0YuT_zzRgaupEaxoVQB5pYVuPnKzrQu2DL2DY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);